[package]
name = "websnark-rs"
version = "0.2.1"
edition = "2024"
description = "Circom v1 transpiler and proof generation library in Rust"
license = "MIT"
repository = "https://github.com/Robert-MacWha/websnark-rs"
readme = "README.md"
keywords = ["snarkjs", "circom", "zk-snark", "websnark"]
categories = ["cryptography", "cryptography::cryptocurrencies"]
exclude = ["*/testdata/**/*", ".gitignore"]

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]
features = []

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
asm = ["ark-ff/asm"]
parallel = [
    "wasm-bindgen-rayon",
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-poly/parallel",
]

[dependencies]
anyhow = { workspace = true }
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
ark-serialize = { workspace = true }
ark-std = { workspace = true }
lalrpop-util = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-rayon = { workspace = true, optional = true }
wasm-bindgen-test = { workspace = true }

[build-dependencies]
lalrpop = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tracing-test = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "proof"
harness = false

[[bench]]
name = "witness"
harness = false

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = ['-O', '-g']
