[package]
name = "websnark-cli"
version = "0.6.0"
edition = "2024"
description = ""
license = "MIT"
publish = false

[dependencies]
clap = { workspace = true, features = ["derive"] }
websnark-rs = { workspace = true, features = ["serde"] }
serde_json = { workspace = true }
postcard = { workspace = true, features = ["use-std"] }
