name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}

    - uses: Swatinem/rust-cache@v2

    - run: nix develop .#ci --command cargo check
    - run: nix develop .#ci --command cargo test
    - run: nix develop .#ci --command cargo bench --features "parallel"

  test-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}

    - uses: Swatinem/rust-cache@v2

    - run: nix develop .#ci --command cargo check --target wasm32-unknown-unknown
    - run: nix develop .#ci --command cargo bench --target wasm32-unknown-unknown
